### ISSUE TITLE
这个情况是缺少依赖吗？

### ISSUE THREAD

**Issue by sayri23** [fz6m/5000choyen-server#2]
![-6e5650e07d032f6f](https://user-images.githubusercontent.com/62638560/118997274-207cba00-b9bb-11eb-823d-322bb1f4472b.jpg)

**Comment by fz6m** [comment]
是的，没装好依赖，在运行一次 `yarn` 把依赖装齐，没有红色报错即可，慢的话先设定淘宝源。
