### ISSUE TITLE
汉字编码应该如何解决？

### ISSUE THREAD

**Issue by Nthily** [fz6m/5000choyen-server#3]
![image](https://user-images.githubusercontent.com/31311826/119551340-d2d8c680-bd99-11eb-933a-582b71e168b6.png)

**Comment by fz6m** [comment]
感谢提出问题。

建议使用 unix 系统或 macOS 部署项目，同时使用国际通用 utf8 编码，本项目暂不会对 windows 下产生的各种问题提供解决方案。
